### PR TITLE
Adds new miojo recipe

### PR DESCRIPTION
**Pull request by DaneOnishi**

### CODE REVIEW

**Review by enzomaruffa — APPROVED** [review]
LGTM

**Comment by pastre** [comment]
👀 💥

**Comment by enzomaruffa** [comment]
> 👀 💥

We're open to new contributors! We have a Contribution guide on the backlog, but as you can see the project is quite simple!

**Comment by pastre** [comment]
Ok! Do you guys need some help with translations?? I also noticed some typos, gonna cook up a PR for that! I can add CI that will cook recipes for us, hope that's useful, I made a robot

**Comment by DaneOnishi** [comment]
It will be extra helpful we were just looking for a miojo pastry chef!!!!

**Pull request merged**
